### ISSUE TITLE
Adding Unit Test cases using Jest Testing Library

### ISSUE THREAD

**Issue by Jagroop2000** [Vita-App/Vita#160]
### Description

**Subject:** Request for Jest integration in ReactJS projects on GitHub
**Hi there !!**

I am writing to request the **integration of Jest**, a popular JavaScript testing library, into your project that uses ReactJS. This would allow developers to write and run unit tests for their React components directly on the platform. Jest's simplicity and power would greatly improve the development experience and increase the reliability of code.

And the good thing is Jest testing files wouldn't add any memory consumption to the project when we make a build or it is on production.
Please add **hard level label** under **JWoC** to this or you can decide it while merging or reviewing PR request.
Thank you for considering this request. I look forward to your response.

Best regards,
Jagroop

### Domain

Full Stack

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Lalit3716** [comment]
Hey Jagroop issues opened before 15th Feb will be considered invalid for JWOC so I am closing this issue for now, please raise it again strictly after 15th February 00:00 AM. Also, I think unit tests are very important and was planning to open an issue for it myself anyways. But since our project is using Vite I think we should go with Vitest as our testing framework!
